### ISSUE TITLE
Error: in <module> .subscribe(lambda s: print(s))

### ISSUE THREAD

**Issue by donhuvy** [thomasnield/oreilly_reactive_python_for_data#1]
I run file [4.4A_twitter_observable.py](https://raw.githubusercontent.com/thomasnield/oreilly_reactive_python_for_data/master/code_examples/4.4A_twitter_observable.py) (original content, no touch)
It makes exception/error
```
/Users/donhuvy/vy_temp/funny_api/venv/bin/python /Users/donhuvy/vy_temp/funny_api/4.4A_twitter_observable.py
Traceback (most recent call last):
  File "/Users/donhuvy/vy_temp/funny_api/4.4A_twitter_observable.py", line 40, in <module>
    .subscribe(lambda s: print(s))
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 83, in subscribe
    current_thread_scheduler.schedule(set_disposable)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 50, in schedule
    return self.schedule_relative(timedelta(0), action, state)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 67, in schedule_relative
    Trampoline.run(queue)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/concurrency/currentthreadscheduler.py", line 31, in run
    item.invoke()
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/concurrency/scheduleditem.py", line 17, in invoke
    ret = self.scheduler.invoke_action(self.action, self.state)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/concurrency/schedulerbase.py", line 14, in invoke_action
    ret = action(self, state)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/linq/observable/select.py", line 38, in subscribe
    return self.subscribe(on_next, observer.on_error, observer.on_completed)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 85, in subscribe
    set_disposable()
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/linq/observable/where.py", line 44, in subscribe
    return parent.subscribe(on_next, observer.on_error, observer.on_completed)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 85, in subscribe
    set_disposable()
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/linq/observable/select.py", line 38, in subscribe
    return self.subscribe(on_next, observer.on_error, observer.on_completed)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 85, in subscribe
    set_disposable()
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/linq/connectableobservable.py", line 49, in subscribe
    connectable_subscription[0] = source.connect()
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/linq/connectableobservable.py", line 29, in connect
    disposable = self.source.subscribe(self.subject)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 85, in subscribe
    set_disposable()
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/linq/observable/asobservable.py", line 17, in subscribe
    return source.subscribe(observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 85, in subscribe
    set_disposable()
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observablebase.py", line 67, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobservable.py", line 20, in _subscribe_core
    return self._subscribe(observer)
  File "/Users/donhuvy/vy_temp/funny_api/4.4A_twitter_observable.py", line 30, in observe_tweets
    stream.filter(track=topics)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/tweepy/streaming.py", line 249, in _run
    if self.listener.on_error(resp.status_code) is False:
  File "/Users/donhuvy/vy_temp/funny_api/4.4A_twitter_observable.py", line 23, in on_error
    observer.on_error(status)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/subjects/subject.py", line 75, in on_error
    observer.on_error(exception)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 17, in _on_error_core
    self._error(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 17, in _on_error_core
    self._error(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 17, in _on_error_core
    self._error(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/autodetachobserver.py", line 23, in _on_error_core
    self.observer.on_error(exn)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/observerbase.py", line 33, in on_error
    self._on_error_core(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/core/anonymousobserver.py", line 17, in _on_error_core
    self._error(error)
  File "/Users/donhuvy/vy_temp/funny_api/venv/lib/python3.6/site-packages/rx/internal/basic.py", line 35, in default_error
    raise Exception(err)
Exception: 401

Process finished with exit code 1
```

**Comment by thomasnield** [comment]
That is a 401 exception. You need to set up a Twitter API account which is discussed later in the course. If you did that already and are still having issues,  try resetting your system clock.

**Comment by donhuvy** [comment]
Thank you!
